server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///library?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 321
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl